/* tslint:disable */
/* eslint-disable */
/**
 * Reit Africa Backend Service
 * This service provides endpoints for all related interactions
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: marv@reit-africa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

