name: Generate API clients from spec
on: 
  push:
    paths:
      - 'spec/**'

env:
  GITHHUB_TOKEN: ${{secrets.COMMIT_TOKEN}}

jobs:
  generateClientSource:
    name: Generate Client Source
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: package-lock.json
      
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Download OpenAPI Generator CLI
        run: |
          wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/5.3.1/openapi-generator-cli-5.3.1.jar -O openapi-generator-cli.jar

      - name: Run Make Script
        run: sh generate.sh